### ISSUE TITLE
Explanation of Truncation?

### ISSUE THREAD

**Issue by miretchin** [ulf1/sklearn-fracdiff#4]
Hello!

Are you familiar with this package? https://github.com/simaki/fracdiff

They don't appear to require that the output is truncated. What is the reason for the truncation that results in this package? I would prefer to use yours because it's faster, but I don't understand why the results are truncated (NaNs at start of sequence). Thanks!

**Comment by miretchin** [comment]
Actually, it looks like the user is supposed to supply a window which I guess is how they determine the truncation size. What is the advantage of inferring the truncation size from the data?

**Comment by ulf1** [comment]
The other package calls it `window`
see https://github.com/simaki/fracdiff/blob/master/fracdiff/fracdiff.py#L91

In the literature it's called "truncation order". Theoretically fractal differentiation assumes an infinite number of past observations but in practice you need to chop or truncate the historic information at some point. If you truncate after 10 steps into the step, then your "long memory" will not go much beyond.
I usually pick highest possible truncation order, e.g. 500 to 2000. That's obviously a practical problem if you are dealing with daily stock prices.

Here is an implementation of Lopez's (2018) algorithm to find a "good" truncation order: https://github.com/ulf1/numpy-fracdiff/blob/master/numpy_fracdiff/find_truncation.py
and here some code benchmarks
https://github.com/ulf1/numpy-fracdiff/blob/master/examples/profile-find-truncation-order.ipynb

**Comment by ulf1** [comment]
And look @miretchin 
https://github.com/ulf1/sklearn-fracdiff/blob/master/sklearn_fracdiff/fracdiff_class.py#L29

```
...
            else:  # 'find' or None
                _, self.weights = find_truncation(
                    self.order, tau=self.tau, mmax=self.mmax)
...
```

`sklearn_fracdiff.FracDiff` will "automagically" compute a "good" truncation order for you (using Lopez's algorithm). However, only the `weights` are stored. Maybe we store `self.truncation` as well, e.g.

```
...
            else:  # 'find' or None
                self.truncation, self.weights = find_truncation(
                    self.order, tau=self.tau, mmax=self.mmax)
...
```

This might be useful information.

**Comment by ulf1** [comment]
"What is the advantage of inferring the truncation size from the data?"

the required truncation order (or window size) depends on the desired fractal order "d".
